# fly.toml app configuration file generated for zinmaseeds-app on 2023-08-18T21:57:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zinmaseeds-app"
primary_region = "eze"
console_command = "/rails/bin/rails console"

[build]



[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
